version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./images/node-Dockerfile     
    env_file:
      - .env 
    depends_on: 
      - db  
    networks:
      - fullcycle  

  nginx:
    build:
      context: .
      dockerfile: ./images/nginx-Dockerfile
    ports:
      - 8082:8082  
    env_file:
      - .env  
    depends_on: 
      - node  
    networks:
      - fullcycle   

  db:
    image: mysql
    restart: always 
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}  
      - MYSQL_USER=${DATABASE_USER}  
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}  
      - MYSQL_ROOT_PASSWORD=${DATABASE_USER_PASSWORD}
    command:
      #- mysql -e "ALTER USER '${DATABASE_USER}' IDENTIFIED WITH mysql_native_password BY '${DATABASE_USER_PASSWORD}'"  
    expose:
      - 3306
    env_file:
      - .env
    volumes:  
      - ./db/:/docker-entrypoint-initdb.d/
    networks:
      - fullcycle

networks:
  fullcycle:  
    driver: bridge    






