version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./images/node-Dockerfile     
    env_file:
      - .env 
    depends_on: 
      db:
       condition: service_healthy      
    networks:
      - fullcycle   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$NODE_PORT"]
      interval: 20s
      timeout: 10s
      retries: 3     
    volumes:
      - ./src/main.js:/app/main.js      

  nginx:
    build:
      context: .
      dockerfile: ./images/nginx-Dockerfile
    ports:
      - 8080:$NGINX_PORT  
    env_file:
      - .env       
    networks:
      - fullcycle   
    depends_on: 
      node:
       condition: service_healthy   

  db:
    image: mysql:5.7
    restart: always 
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}  
      - MYSQL_USER=${DATABASE_USER}  
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}  
      - MYSQL_ROOT_PASSWORD=${DATABASE_USER_PASSWORD}    
    expose:
      - 3306
    env_file:
      - .env
    volumes:  
      - ./db/:/docker-entrypoint-initdb.d/  
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER -p$$MYSQL_PASSWORD ping -h localhost"]
      interval: 20s
      timeout: 10s
      retries: 3  
    networks:
      - fullcycle

networks:
  fullcycle:  
    driver: bridge    






